### ISSUE TITLE
Any plans to update to scikit-learn 1.5.0?

### ISSUE THREAD

**Issue by tianhuil** [thenovices/heroku-buildpack-scipy#11]
This project is great!  Are there any plans to upgrade to the new scikit-learn?

**Comment by andrewychoi** [comment]
@tianhuil Not sure if you got this fixed, but I'm able to compile `scikit-learn==0.15.2` from inclusion in `requirements.txt` without needing a precompiled binary:
```
$ heroku run -a cedar-app python
Running `python` attached to terminal... up, run.xxxx
Python 2.7.6 (default, Jan 16 2014, 02:39:37) 
[GCC 4.4.3] on linux2
>>> import sklearn
>>> sklearn.__version__
'0.15.2'
```
Also using the updated `cedar-14` stack (with Python 2.7.9):
```
$ heroku run -a cedar-14-app python
Running `python` attached to terminal... up, run.xxxx
Python 2.7.9 (default, Dec 11 2014, 17:18:51) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
>>> sklearn.__version__
'0.15.2'
```
We're using some of the `sklearn.linear_model` stuff and it seems to be working okay.

**Comment by thenovices** [comment]
I haven't tried it, but if it works for Andrew then I'm guessing it should work for others.

If you try it out, definitely run the full test suite to make sure you feel confident it works.

**Comment by anitameh** [comment]
Hey @andrewychoi what version of scipy and numpy were you using to get `scikit-learn==0.15.2` working?
