### ISSUE TITLE
Error while import hierarchy

### ISSUE THREAD

**Issue by stripathi669** [thenovices/heroku-buildpack-scipy#16]
Hi,

On the heroku app, I compiled Scipy 0.13.3 with Numpy 1.9 using the toolbelt. Now I am getting following error when import `hiegharchy`. Here's the the tracestack:     

    from . import vq, hierarchy
      File "/app/.heroku/python/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 175, in <module>
    from . import _hierarchy_wrap
    ImportError: cannot import name _hierarchy_wrap

**Comment by thenovices** [comment]
Sorry, I wasn't able to replicate your issue. Could you please post your requirements.txt, and the line that the import fails on?

I ran a minimal installation of numpy 1.9.0 and scipy 0.13.0, opened a python shell, and `import scipy.cluster.hiearchy` worked just fine.

**Comment by thenovices** [comment]
I'm going to close this issue for now. Please reopen if you can provide more information about your error.
