### ISSUE TITLE
build scripts for binaries

### ISSUE THREAD

**Issue by jtarchie** [thenovices/heroku-buildpack-scipy#28]
Could you please provide the building and packaging scripts for NumPy, SciPy, and the dependencies? I checked [here](https://github.com/thenovices/npscipy-binaries), but was unable to find them.

It would be great to verify how they are be compiled and with what compile time options.

Thanks!

**Comment by andrewychoi** [comment]
@jtarchie, unsure about these specific packages, but there's a couple of vagrant scripts here: https://github.com/andrewychoi/npscipy-binaries/tree/master/vagrant

**Comment by jtarchie** [comment]
How were they able to recreate the newer versions then? It looks like the only way would be updating these scripts with the version numbers.

**Comment by andrewychoi** [comment]
Yep! That's how I did the updating.
